-- A3. View the list of users in the system
SELECT * FROM all_users;

-- A4. Information about the privileges of each user / role on data objects
SELECT * FROM  USER_TAB_PRIVS WHERE TABLE_NAME = 'CHAMCONG' OR  TABLE_NAME = 'BENHNHAN'
OR  TABLE_NAME = 'HOSOBENHNHAN' OR  TABLE_NAME = 'HOSODICHVU' OR  TABLE_NAME = 'HOADON'
OR  TABLE_NAME = 'NHANVIEN' OR  TABLE_NAME = 'DONVI' OR  TABLE_NAME = 'DONTHUOC'
OR  TABLE_NAME = 'DICHVU' OR  TABLE_NAME = 'CTHOADON' OR  TABLE_NAME = 'CTDONTHUOC'
OR  TABLE_NAME = 'THUOC';

-- A6





-- TEST
SELECT * FROM DBA_SYS_PRIVS;
SELECT * FROM  DBA_ROLE_PRIVS;

SELECT * FROM  ALL_COL_PRIVS;
SELECT * FROM  USER_TAB_PRIVS;



