

CREATE OR REPLACE TRIGGER TRIG_UPDATE_EMP_SAL
BEFORE UPDATE OF SAL
ON EMP_COPY
FOR EACH ROW
DECLARE 
BEGIN
    AUDIT_EMP(
        P_USERNAME => USER,
        P_ACTION =>  'UPDATE',
        P_EMPNO =>  :OLD.EMPNO,
        P_COLUMN_NAME => 'SAL',
        P_OLD_VALUE => TO_CHAR(:OLD.SAL),
        P_NEW_VALUE => TO_CHAR(:NEW.SAL)        
    );
END;

SELECT * FROM DUCCAO_ADMIN.NHANVIEN;

/*********************
*       Audit
**********************/

/*
* Table audit luong nhanvien
*/

CREATE TABLE AUDIT_LUONG_NHANVIEN(
    USERNAME VARCHAR2(200),
    ACTION VARCHAR2(200),
    MANV VARCHAR2(200),
    COLUMN_NAME VARCHAR2(200),
    OLD_VALUE VARCHAR2(200),
    NEW_VALUE VARCHAR2(200),
    CALL_STACK VARCHAR2(4000),
    CLIENT_ID VARCHAR2(200),
    ACTION_DATE DATE DEFAULT SYSDATE
);

/*
* procerdure audit luong nhanvien
*/
CREATE OR REPLACE PROCEDURE PROC_AUDIT_LUONG_NHANVIEN(
    P_USERNAME IN VARCHAR2,
    P_ACTION IN VARCHAR2,
    P_MANV IN VARCHAR2,
    P_COLUMN_NAME IN VARCHAR2,
    P_OLD_VALUE IN VARCHAR2,
    P_NEW_VALUE IN VARCHAR2
)
AS 
BEGIN
    INSERT INTO AUDIT_LUONG_NHANVIEN (USERNAME,ACTION,MANV,COLUMN_NAME,
    OLD_VALUE,NEW_VALUE,CALL_STACK,CLIENT_ID,ACTION_DATE)
    VALUES (P_USERNAME,P_ACTION,P_MANV,P_COLUMN_NAME,P_OLD_VALUE,P_NEW_VALUE,
    DBMS_UTILITY.FORMAT_CALL_STACK,SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),SYSDATE);
END;
/


/*
* procerdure show audit luong nhanvien
*/
CREATE OR REPLACE PROCEDURE SHOW_AUDIT_LUONG_NHANVIEN
AS
BEGIN
    FOR REC IN (
        SELECT * 
        FROM DUCCAO_ADMIN.AUDIT_LUONG_NHANVIEN
        ORDER BY ACTION_DATE DESC)
    LOOP
        DBMS_OUTPUT.PUT_LINE('User: '||rec.username);
        DBMS_OUTPUT.PUT_LINE('Client ID: '||rec.CLIENT_ID);
        DBMS_OUTPUT.PUT_LINE('Action: '||rec.ACTION);
        DBMS_OUTPUT.PUT_LINE('MANV: '||rec.MANV);
        DBMS_OUTPUT.PUT_LINE('COLUMN_NAME: '||rec.COLUMN_NAME);
        DBMS_OUTPUT.PUT_LINE('OLD_VALUE: '||rec.OLD_VALUE);
        DBMS_OUTPUT.PUT_LINE('NEW_VALUE: '||rec.NEW_VALUE);
        DBMS_OUTPUT.PUT_LINE('CALL_STACK: '||rec.CALL_STACK);
        DBMS_OUTPUT.PUT_LINE('DAY: '||TO_CHAR(rec.ACTION_DATE,'Mon-DD-YY HH24:MI'));
    END LOOP;
END;
/


/*
* trigger audit luong nhanvien
*/
CREATE OR REPLACE TRIGGER TRIG_UPDATE_NHANVIEN_LUONG
BEFORE UPDATE OF LUONG
ON DUCCAO_ADMIN.NHANVIEN
FOR EACH ROW
DECLARE
BEGIN
      PROC_AUDIT_LUONG_NHANVIEN(
        P_USERNAME => USER,
        P_ACTION =>  'UPDATE',
        P_MANV =>  :OLD.MANV,
        P_COLUMN_NAME => 'LUONG',
        P_OLD_VALUE => TO_CHAR(:OLD.LUONG),
        P_NEW_VALUE => TO_CHAR(:NEW.LUONG)        
    );
END;



/*********************
*       End Audit
**********************/







