ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

DROP USER U1;
DROP USER U2;

DROP ROLE R1;
DROP ROLE R2;


DROP USER USER_NHANVIEN_QUANLY_TV01 ;
DROP USER USER_NHANVIEN_QUANLY_TV02 ;
DROP USER USER_NHANVIEN_QUANLY_TV03 ;

DROP USER USER_NHANVIEN_THUTHU_TV01_01;
DROP USER USER_NHANVIEN_THUTHU_TV01_02;
DROP USER USER_NHANVIEN_THUTHU_TV02_01;
DROP USER USER_NHANVIEN_THUTHU_TV02_02 ;
DROP USER USER_NHANVIEN_THUTHU_TV03_01 ;
DROP USER USER_NHANVIEN_THUTHU_TV03_02 ;

DROP USER DUCCAO_01 ;
DROP USER DUCCAO_02 ;
DROP USER DUCCAO_03 ;


DROP USER JOHN ;
DROP USER JOE ;
DROP USER FRED ;
DROP USER LYNN ;
DROP USER AMY ;
DROP USER BETH ;

DROP TABLE JOHN.JOIN_TBL;
DROP TABLESPACE TBS_HW32USERS;
DROP TABLE  ATTENDANCE;


DROP ROLE DATAENTRY;
DROP ROLE SUPERVISOR;
DROP ROLE MANAGEMENT;

DROP USER NameManager;

-- PROJECT
DROP ROLE role_dep_letan;

DROP USER user_tieptan_01;
DROP USER user_tieptan_02;

DROP ROLE ROLE_DOCTOR;

DROP USER USER_BACSI_01;
DROP USER USER_BACSI_02;
