/*****************************
--- A. Admin Test
/*****************************/

---------------------------------------------
--- 1. Test Select grant with column level
------------------------------------------------
CONN U1/U1;
SELECT * FROM DUCCAO_ADMIN.VW_USER_SELECT_COLUMN_LEVEL_U1_NGAYKB_HOSOBENHNHAN;

CONN U1/U1;
GRANT SELECT ON DUCCAO_ADMIN.VW_USER_SELECT_COLUMN_LEVEL_U1_NGAYKB_HOSOBENHNHAN TO U2;

CONN U2/U2;
SELECT * FROM DUCCAO_ADMIN.VW_USER_SELECT_COLUMN_LEVEL_U1_NGAYKB_HOSOBENHNHAN;

---------------------------------------------
--- 2. Test Select grant with role level
------------------------------------------------
GRANT R2 TO U2;

CONN U2/U2;
SET ROLE R2 IDENTIFIED BY R2;
SELECT * FROM DUCCAO_ADMIN.VW_ROLE_SELECT_COLUMN_LEVEL_R2_MANV_HOSOBENHNHAN;






/*****************************
--- B. Users In System Test
/*****************************/



--------------------------------
--- 1. TEST RECEPTION ROLE 
--------------------------------

-- 1.1 Cannot view the 'donGia' field in table Dichvu
CONN USER_TEPTAN_01/USER_TEPTAN_01;
SET ROLE ROLE_DEP_LETAN IDENTIFIED  BY ROLE_DEP_LETAN;
SELECT * FROM DUCCAO_ADMIN.VW_DEP_LETAN_DICHVU;


-- 1.2 Can Select on table BENHNHAN
CONN USER_TEPTAN_01/USER_TEPTAN_01;
SET ROLE ROLE_DEP_LETAN IDENTIFIED  BY ROLE_DEP_LETAN;
SELECT * FROM DUCCAO_ADMIN.BENHNHAN;

-- 1.3 Can Insert on table BENHNHAN
CONN USER_TEPTAN_01/USER_TEPTAN_01;
SET ROLE ROLE_DEP_LETAN IDENTIFIED  BY ROLE_DEP_LETAN;
INSERT INTO DUCCAO_ADMIN.BENHNHAN (MABN,HOTEN,NGAYSINH,DIACHI,SDT)
VALUES (15,'BN10',TO_DATE('12/12/1999','MM/DD/YYYY'),'HCM','123123123');


-- 1.4 Can Update on table BENHNHAN
CONN USER_TEPTAN_01/USER_TEPTAN_01;
SET ROLE ROLE_DEP_LETAN IDENTIFIED  BY ROLE_DEP_LETAN;
UPDATE DUCCAO_ADMIN.BENHNHAN SET DIACHI = 'HCM UPDATED' WHERE MABN=15;


-- 1.5 Can Select on table HOSOBENHNHAN
CONN USER_TEPTAN_01/USER_TEPTAN_01;
SET ROLE ROLE_DEP_LETAN IDENTIFIED  BY ROLE_DEP_LETAN;
SELECT * FROM DUCCAO_ADMIN.HOSOBENHNHAN;

-- 1.6 Can Insert on table HOSOBENHNHAN
CONN USER_TEPTAN_01/USER_TEPTAN_01;
SET ROLE ROLE_DEP_LETAN IDENTIFIED  BY ROLE_DEP_LETAN;
INSERT INTO DUCCAO_ADMIN.HOSOBENHNHAN (MAKB, NGAYKB, TENBACSI, MABN, TINHTRANGBANDAU)   
VALUES (15,TO_DATE('12/12/1999','MM/DD/YYYY'),'USER_BACSI_01',1,'HO');


-- 1.7 Can Update on table HOSOBENHNHAN
CONN USER_TEPTAN_01/USER_TEPTAN_01;
SET ROLE ROLE_DEP_LETAN IDENTIFIED  BY ROLE_DEP_LETAN;
UPDATE DUCCAO_ADMIN.HOSOBENHNHAN SET TINHTRANGBANDAU = 'HO UPDATED' WHERE MAKB=15;


-- Check Role Priv
CONN USER_TEPTAN_01/USER_TEPTAN_01;
SELECT * FROM DUCCAO_ADMIN.VW_DEP_LETAN_DICHVU;


-------------------------------------
--- 2. TEST ACCOUNTING DEPARMENT ROLE
------------------------------------

-- 2.1 User in Ketoan can Select on CHAMCONG
CONN USER_KETOAN_01/USER_KETOAN_01;
SET ROLE ROLE_DEP_KETOAN IDENTIFIED BY ROLE_DEP_KETOAN;
SELECT * FROM DUCCAO_ADMIN.CHAMCONG;

-- 2.2 User in Ketoan ca UPDATE 'LUONG' field on tbl NHANVIEN
CONN USER_KETOAN_01/USER_KETOAN_01;
SET ROLE ROLE_DEP_KETOAN IDENTIFIED BY ROLE_DEP_KETOAN;
UPDATE DUCCAO_ADMIN.NHANVIEN SET LUONG ='20.000.000' WHERE MANV = 'bs01';




-------------------------------
--- 3. TEST DOCTOR ROLE
----------------------------
-- USER_BACSI_01

-- p1. Only SELECT patient information for their responsibility
SELECT * FROM DUCCAO_ADMIN.HOSOBENHNHAN;

CONN USER_BACSI_01/USER_BACSI_01;
SET ROLE ROLE_DOCTOR IDENTIFIED  BY ROLE_DOCTOR;
SELECT * FROM DUCCAO_ADMIN.HOSOBENHNHAN;


-- p1. Only UPDATE patient information for their responsibility
CONN USER_BACSI_01/USER_BACSI_01;
SET ROLE ROLE_DOCTOR IDENTIFIED  BY ROLE_DOCTOR;
UPDATE DUCCAO_ADMIN.HOSOBENHNHAN SET KETLUANCUABACSI ='KHOE MANH!' WHERE MAKB = 1 ;

-- P2. Only SELECT, INSERT, UPDATE ON CTDONTHUOC for their responsibility
-- SELECT
CONN USER_BACSI_01/USER_BACSI_01;
SET ROLE ROLE_DOCTOR IDENTIFIED  BY ROLE_DOCTOR;
SELECT * FROM DUCCAO_ADMIN.VIEW_VPD_DOCTOR_CTDONTHUOC;




-------------------------------
--- 4. TEST Management Department
----------------------------

-- P1.Insert on NHANVIEN
CONN USER_TAINGUYEN_NHANSU_01/USER_TAINGUYEN_NHANSU_01;
SET ROLE ROLE_DEP_QL_TG_NS IDENTIFIED BY ROLE_DEP_QL_TG_NS;
INSERT INTO DUCCAO_ADMIN.NHANVIEN(MANV, HOTEN, MATKHAU) VALUES ('NV100','NHAN_VIEN_100','NV100');


--  P2. SELECT  on VW_DEP_QL_TAINGUYEN_NHANSU 
CONN USER_TAINGUYEN_NHANSU_02/USER_TAINGUYEN_NHANSU_02;
SET ROLE ROLE_DEP_QL_TG_NS IDENTIFIED BY ROLE_DEP_QL_TG_NS;
SELECT * FROM DUCCAO_ADMIN.VW_DEP_QL_TAINGUYEN_NHANSU;



SHOW USER;
SELECT SYS_CONTEXT('USERENV','SESSION_USER') FROM DUAL ;





