CREATE USER SCOTT IDENTIFIED BY SCOTT;
GRANT CREATE SESSION TO SCOTT;
GRANT CREATE TABLE TO SCOTT;

CONN SCOTT/SCOTT;
CREATE TABLE announcements (MESSAGE VARCHAR2(4000));

CONN LBACSYS/LBACSYS;
EXECUTE SA_SYSDBA.CREATE_POLICY('ACCESS_NHANVIEN','OLS_NHANVIEN');

CONN LBACSYS/LBACSYS;
BEGIN
sa_sysdba.create_policy
(policy_name => 'ESBD',
column_name => 'rowlabel');
END;

--  -- This procedure registers Oracle Label Security.
EXEC LBACSYS.CONFIGURE_OLS;
 -- This procedure enables it.
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;

shutdown immediate;
startup;

SELECT * FROM DBA_OLS_STATUS WHERE NAME = 'OLS_CONFIGURE_STATUS';



ALTER USER LBACSYS ACCOUNT UNLOCK IDENTIFIED BY LBACSYS;


